blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
from django.conf import settings
from django.views.static import serve
from app01.views import pcgetcaptcha,pcajax_validate
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    #url(r'^login/', views.login),
    url(r'^reg/', views.reg),
    url(r'^$', views.index),
    url(r'^get_valid_Code_img/', views.get_valid_Code_img),
    url(r'^logout/', views.logout),
    url(r'^changePassword/', views.changePassword),

    url(r'^cate/(?P<site_article_category>.*)/$', views.index),  # # index(requset,site_article_category=python)


    #个人站点首页
    url(r'^blog/',include("app01.urls") ),
    url(r'^backManage/',include("backManage.urls") ),

    #media配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    # 滑动验证码配置

    url(r'^pc-geetest/register', pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^pc-geetest/ajax_validate', pcajax_validate, name='pcajax_validate'),

]

app01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Userinfo(AbstractUser):
    '''
    用户表
    '''
    id=models.BigAutoField(primary_key=True)

    nickname=models.CharField(max_length=32,verbose_name="昵称")
    phone = models.CharField(max_length=11,blank=True,null=True,unique=True, verbose_name="电话")
    avatar = models.FileField(verbose_name='头像', upload_to='avatar', default="/avatar/default.png")
    registTime = models.DateTimeField(verbose_name="注册时间",auto_now_add=True)

    class Meta:
        verbose_name_plural="用户表"

    def __str__(self):
        return self.username

class Blog(models.Model):
    '''
    博客表
    '''
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    user = models.OneToOneField(to='Userinfo', to_field='id')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural="博客表"

class Category(models.Model):
    """
    博主个人文章分类表
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='id')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = '文章分类表'
        ordering = ['title']

class Article(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    read_count = models.IntegerField(default=0,verbose_name='阅读数')
    comment_count = models.IntegerField(default=0,verbose_name="评论数")
    up_count = models.IntegerField(default=0,verbose_name="点赞数")
    down_count = models.IntegerField(default=0,verbose_name="差评数")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='id', null=True)
    user = models.ForeignKey(verbose_name='所属用户', to='Userinfo', to_field='id')
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    siteArticleCategory=models.ForeignKey(to="SiteArticleCategory",verbose_name="所属网站文章分类",null=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural="文章表"

class ArticleDetail(models.Model):
    """
    文章详细表
    """
    id = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='id')

    class Meta:
        verbose_name_plural="文章详细表"

    def __str__(self):
        return self.article.title

class Comment(models.Model):
    """
    评论表
    """
    id = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='评论者', to='Userinfo', to_field='id')
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='id')

    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural="评论表"

class CommentUp(models.Model):
    """
    评论点赞表
    """

    id = models.AutoField(primary_key=True,verbose_name='评论点赞id')
    user = models.ForeignKey('Userinfo', null=True,verbose_name="点赞人")
    comment = models.ForeignKey("Comment", null=True,verbose_name="点赞的评论")

    class Meta:
        verbose_name_plural='评论点赞表'




class ArticleUp(models.Model):
    """
    文章点赞表
    """
    id = models.AutoField(primary_key=True,verbose_name='文章点赞id')
    user = models.ForeignKey('Userinfo', null=True,verbose_name='点赞人')
    article = models.ForeignKey("Article", null=True,verbose_name="点赞的文章")

    class Meta:
        verbose_name_plural="文章点赞表"

class ArticleDown(models.Model):
    """
    文章反对表
    """
    id = models.AutoField(primary_key=True,verbose_name='文章反对id')
    user = models.ForeignKey('Userinfo', null=True,verbose_name='反对人')
    article = models.ForeignKey("Article", null=True,verbose_name="反对的文章")

    class Meta:
        verbose_name_plural="文章反对表"

class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='id')

    class Meta:
        verbose_name_plural="标签表"

    def __str__(self):
        return  self.title

class Article2Tag(models.Model):
    id = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='id')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='id')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

        verbose_name_plural='文章和标签关联表'

class SiteCategory(models.Model):
    '''
    网站分类
    '''
    name=models.CharField(max_length=32,verbose_name='网站分类名称')
    class Meta:
        verbose_name_plural='网站分类表'

    def __str__(self):
        return self.name


class SiteArticleCategory(models.Model):
    '''
    网站分类对应的文章分类表
    '''
    name=models.CharField(max_length=32,verbose_name="网站文章分类名称")

    siteCategory=models.ForeignKey(to="SiteCategory",verbose_name='所属网站分类')

    class Meta:
        verbose_name_plural='网站文章分类表'

    def __str__(self):
        return self.name

templates/article.html
{% extends "personalBase.html" %}

{% block css %}
    <link rel="stylesheet" href="/static/css/article.css">
{% endblock css %}



{% block article %}
    <div class="article">
        <div id="body">
            <div id="article_title">
                <h1><a href="">{{ articleobj.title }}</a></h1>
            </div>
            <div id="article_id" class="hide">{{ articleobj.id }}</div>
            <div id="article_content">
                {{ articleobj.articledetail.content|safe }}
            </div>

            <div id="article_opration">
                <div id="BlogPostCategory">
                    分类:<a
                        href="/blog/{{ articleobj.user.username }}/category/{{ articleobj.category.title }}">{{ articleobj.category.title }}</a>
                </div>
                <div id="green_channel">
                    <a id="green_channel_digg">好文要顶</a>
                    <a id="green_channel_follow">关注我</a>
                    <a id="green_channel_favorite">收藏该文</a>
                    <a id="green_channel_weibo">
                        <img src="/static/img/icon_weibo_24.png" alt="">
                    </a>
                    <a id="green_channel_wechat">
                        <img src="/static/img/wechat.png" alt="">
                    </a>
                </div>
                <div id="author_profile">
                    <a href="/blog/{{ articleobj.user.username }}/" id="avatar_avatar"><img
                            src="/media/{{ articleobj.user.avatar }}" alt=""></a>
                    <div id="arthor_deatil">
                        <a href="/blog/{{ articleobj.user.username }}/">{{ articleobj.user.nickname }}</a> <br>
                        <a href="">关注:5</a> <br>
                        <a href="">粉丝:300</a> <br>
                    </div>
                    <div id="div_digg">
                        <div class="diggit">
                            {% csrf_token %}
                            <span class="diggnum" id="digg_count">{{ articleobj.up_count }}</span>
                        </div>

                        <div class="buryit">
                            <span class="burynum" id="bury_count">{{ articleobj.down_count }}</span>
                        </div>
                        <div class="clear"></div>
                        <div class="diggword" id="digg_tips">
                        </div>
                        <span class="pull-right" style="margin-right: 20px" id="uperror"></span>
                    </div>

                    <div id="post_next_prev"><a href="" class="p_n_p_prefix">« </a>
                        上一篇：<a href="" title="发布于2017-11-14 23:25">Django-Ajax</a><br></div>

                    <div class="postDesc pull-right">
                        posted @ <span id="post-date">{{ articleobj.create_time|date:"Y-m-d" }}</span>
                        <a href="/blog/{{ articleobj.user.username }}">{{ articleobj.user.nickname }}</a>
                        阅读 <span id="read_count">({{ articleobj.read_count }})</span> 评论({{ articleobj.comment_count }})
                        <a href="#">编辑</a>
                        <a href="#">收藏</a></div>


                </div>

            </div>

            <div id="comment_list">
                <div id="commentList">评论列表</div>
                <div id="commentTree">

                </div>
                {% for con in articleobj.comment_set.all %}
                    <div class="commentItem">
                        <div class="feedbackManage">

                            &nbsp;&nbsp;<span class="comment_actions">
                            {% if con.user.id == request.user.id %}
                                <a href="#commentBody" comment_id="{{ con.id }}">修改</a>
                                <a comment_id="{{ con.id }}" class="delComment">删除</a>
                            {% else %}
                                <a comment_id="{{ con.id }}" comment_username="{{ con.user.username }}" comment_name="{{ con.user.nickname }}" class="reply">回复</a>
                                <a href="#">引用</a>
                            {% endif %}

                          </span>
                        </div>
                        <div class="commentTile">
                            <a href="#3762185" class="layer">{{ forloop.counter }}楼</a>
                            <img class="user_avatar" src="/media/{{ con.user.avatar }}" alt="">
                            <span>{{ con.create_time|date:"Y-m-d H:i:s" }}</span>
                            <a href="/blog/{{ con.user.username }}/" id="user_nickname">{{ con.user.nickname }}</a>
                        </div>
                        <div class="commentContent">
                            {% if con.parent_comment_id %}
                                   <div class="comment_body_content">
                                     <div>
                                         <a href="/blog/{{ con.parent_comment.user.username }}/">@{{ con.parent_comment.user.nickname }}</a>
                                     </div>
                                    {{ con.content|safe}}
                                   </div>
                                {% else %}
                                 <div class="comment_body_content">

                                {{ con.content|safe}}
                            </div>
                            {% endif %}


                            <div class="comment_vote">
                                <a class="comment_digg"
                                   comment_id="{{ con.id }}">支持(<span>{{ con.up_count }}</span>)</a>
                                <a href="#" class="comment_bury" comment_id="{{ con.id }}">反对(0)</a>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>

            <div id="comment">
                <div id="commentform_title">发表评论</div>
                <div id="comment_nick">
                    <p>
                        昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                                  value="{{ request.user.nickname }}">
                    </p>
                    <p class="hide " id="current_user_avatar">{{ request.user.avatar }}</p>
                </div>
                <div>
                    评论内容
                </div>

                <div id="commentBody">
                    <form>
                        {% csrf_token %}
                        <textarea name="" id="comment_content" cols="40" rows="15" style="width: 800px;height: 400px"></textarea> <br>
                        <input type="button" value="提交评论" id="subBtn">
                    </form>
                </div>
                <span id="commenterror"></span>
            </div>

        </div>
    </div>


    <script>
{#        KindEditor.ready(function (K) {#}
{#            window.editor = K.create('#comment_content', {#}
{#                width: '700px',#}
{#                height: '300px',#}
{#                items: [#}
{#                    'source', 'wordpaste', 'justifyfull', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',#}
{#                    'italic', 'image', 'link', 'emoticons'#}
{#                ]#}
{#            });#}
{#        });#}
    </script>

<script src="/static/js/diggst.js"></script>
{% endblock article %}

templates/backArticleCategory.html
{%  extends "personalManage.html"  %}


{%  block table_tbody %}
 {% for article in articles %}
                           <tr>
                            <td class="post-tilte">
                                <a href="/blog/{{ request.user.username }}/p/{{ article.id }}/" class="post_title">{{ article.title }}</a>
                            </td>
                            <td>发布</td>
                           <td>{{ article.comment_count }}</td>
                           <td>{{ article.read_count }}</td>
                           <td ><a href="" class="delArticle" article_id="{{ article.id }}">删除</a></td>
                           <td><a href="/backManage/editArticle/{{ article.id }}/">编辑</a></td>
                           </tr>
                        {% endfor %}
{% endblock table_tbody %}

templates/categoryEdit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/categotyEdit.css">
</head>
<body>
<nav class="navbar  navbar-fixed-top">
    <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class=" navbar-header" id="navbar-user-nickname">
            <a href="/blog/{{ user.username }}" style="color: white;text-decoration: none"> {{ user.nickname }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right" id="navList">
                <li><a href="/">首页</a></li>
                <li><a href="#">园子</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">收藏</a></li>
                <li><a href="/changePassword/">修改密码</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->


    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid" id="topDiv">
    <div class="row">
        <div class="col-md-2">
            <div>
                <a href="/backManage/addArticle/"> >>添加新随笔</a>
            </div>
        </div>
        <div class="col-md-6">
            <div id="table">
                <table class="table-responsive">
                    <thead>
                    <tr>
                        <th width="200px">分类名称</th>
                        <th width="200px">操作</th>
                    </tr>
                    </thead>
                    <tbody id="tbody">
                    {% for category in request.user.blog.category_set.all %}
                        <tr>
                            <td>{{ category.title }}</td>
                            <td>
                                <button class="btn btn-primary editBtn" category_id="{{ category.id }}">编辑</button>
                                <button class="btn btn-danger delBtn" category_id="{{ category.id }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div id="addCategory" style="margin-top: 50px; ">
                <h3>添加分类</h3>
                <form novalidate>
                    {% csrf_token %}
                    <label for="add_title">分类名称</label>
                    <p><input type="text" name="add_title" id="add_title"></p>
                    <button id="add_btn">提交</button>
                </form>
            </div>
        </div>

        <div class="col-md-4 hide" id="edit_category">
            <p>编辑分类</p>
            <form>
                {% csrf_token %}
                <label for="edit_title">分类名称</label>
                <p><input type="text" name="category_title" id="edit_title"></p>
                <button id="edit_btn">提交</button>
            </form>

        </div>
    </div>
</div>
</body>
<script src="/static/jquery-3.2.1.min.js"></script>
<script>

    $("#add_btn").click(function () {
        $.ajax({
            url: "/backManage/addCategory/",
            type: "POST",
            data: {
                title: $("#add_title").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },

            success: function (data) {
                data = JSON.parse(data);
                if(data.flag){
                    s='<tr>\n' +
                        '                            <td>'+data.category_title+'</td>\n' +
                        '                            <td>\n' +
                        '                                <button class="btn btn-primary editBtn" category_id="'+data.category_id+'">编辑</button>\n' +
                        '                                <button class="btn btn-danger delBtn" category_id="'+data.category_id+'">删除</button>\n' +
                        '                            </td>\n' +
                        '                        </tr>'
                }else{

                }

            }
        })
    })
    $("#tbody").on("click", ".delBtn", function () {

        $tr = $(this).parent().parent();
        if(confirm("你确认要删除吗?")){
            $.ajax({
            url: "/backManage/delCategory/",
            data: {
                id: $(this).attr("category_id")
            },
            success: function (data) {
                if (data == "ok") {
                    $tr.remove()
                }
            }
        })
        }

    })


</script>

<script>
    var category_id = null;
    $("#tbody").on("click", ".editBtn", function () {
        value = $(this).parent().prev().html();
        td = $(this).parent().prev();
        $("#edit_category").removeClass("hide");
        $("#edit_title").val(value);
        category_id = $(this).attr("category_id");
        $("#tbody").data("td", td)
    });

    $("#edit_btn").click(function () {
        $.ajax({
            url: "/backManage/editCategory/",
            type: "POST",
            data: {
                id: category_id,
                title: $("#edit_title").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success: function (data) {
                if (data == "ok") {
                    td.html($("#edit_title").val());

                }
            }
        })

    })

</script>
</html>

templates/personalBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/personalBase.css">
    {% block css %}
    {% endblock css %}
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <script src="/static/kindeditor/lang/zh-CN.js"></script>
{% load myFilter %}
</head>
<body>
<nav class="navbar  navbar-fixed-top">
    <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class=" navbar-header" id="navbar-user-nickname">
            <a href="/blog/{{ user.username }}"  style="color: white;text-decoration: none"> {{ user.nickname }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right" id="navList">
                <li><a href="#">伯乐园</a></li>
                <li><a href="/">首页</a></li>
                <li><a href="/backManage/addArticle/">新随笔</a></li>
                <li><a href="#">联系</a></li>
                <li><a href="#">订阅</a></li>
                <li><a href="/backManage/{{ request.user.username }}/manage/">管理</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid" id="main">
    <div class="row">
        <div class="col-md-3" id="sideBar">
            <div class="panel panel-default">
             <div class="panel panel-default">
                    <div class="panel-heading " id="notice">公告</div>
                    <div class="panel-body">
                        <div id="author_news">
                            <a href=""> <img src="/media/{{ user.avatar }}" alt="" id="author_avatar"></a> <br><br>
                            昵称 : <a href="">{{ user.nickname }}</a> <br>
                            圆龄 : <a href="">{{ user.registTime|yunling }}天</a> <br>
                            粉丝 : <a href="">3000</a> <br>
                            关注 : <a href="">5</a>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">常用链接</div>
                    <div class="panel-body" id="common_link">
                        <ul>
                            <li><a href="">我的随笔</a></li>
                            <li><a href="">我的评论</a></li>
                            <li><a href="">我的参与</a></li>
                            <li><a href="">我的标签</a></li>
                            <li><a href="">最新评论</a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">文章分类</div>
                    <div class="panel-body" id="article_category">
                        <ul>
                            {% for category in user.blog.category_set.all %}
                                <li><a href="/blog/{{ user.username }}/category/{{ category.title }}">{{ category.title }}({{ category.article_set.count }})</a></li>
                            {% endfor %}


                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">标签分类</div>
                    <div class="panel-body" id="article_category">
                        <ul>
                          {% for tag in user.blog.tag_set.all %}
                             <li><a href="/blog/{{ user.username }}/tag/{{ tag.title }}">{{ tag.title }}({{ tag.article_set.all.count}})</a></li>
                          {% endfor %}

                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">随笔档案</div>
                    <div class="panel-body" id="article_category">
                        <ul>
                            {% for date in date_list%}
                                     <li><a href="/blog/{{ user.username }}/date/{{date.0 }}">{{date.0}}({{ date.1 }})</a></li>

                            {% endfor %}


                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-md-9" id="mainContent">


            {% block article %}

            {% endblock article %}

        </div>

    </div>
</div>
</body>
</html>

templates/personalManage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/personalManage.css">
    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <script src="/static/kindeditor/lang/zh-CN.js"></script>

</head>
<body>
<nav class="navbar  navbar-fixed-top">
    <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class=" navbar-header" id="navbar-user-nickname">
            <a href="/blog/{{ user.username }}" style="color: white;text-decoration: none"> {{ user.nickname }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right" id="navList">
                <li><a href="/">首页</a></li>
                <li><a href="#">园子</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">收藏</a></li>
                <li><a href="/changePassword/">修改密码</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->


    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid" id="content_div">
    <div class="row">
        <div class="col-md-2" id="left_content">
            <div class="panel panel-default">
                <div class="panel panel-default">
                    <div class="panel-heading ">操作</div>
                    <div class="panel-body">
                        <div><a href="/backManage/addArticle/">添加新随笔</a></div>
                        <div><a href="">草稿箱</a></div>
                        <div><a href="">设置默认编辑器</a></div>
                        <div><a href="">博客备份</a></div>
                        <div><a href="">博客搬家</a></div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading ">分类</div>
                    <div class="panel-body">
                        <div><a href="/backManage/categotyEdit/">编辑分类</a></div>
                        {% for category in request.user.blog.category_set.all %}
                            <div><a href="/backManage/articleCategory/{{ category.title }}/">{{ category.title }}({{ category.article_set.count }})</a></div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8" id="main_content">
        {% block content %}
            <div id="tab_nav">
                <ul>
                    <li><a id="TabPosts" href="" class="current_nav">随笔</a></li>
                    <li><a id="TabArticles" href="">文章</a></li>
                    <li><a id="TabDiary" href="">日记</a></li>
                    <li><a id="TabFeedback" href="">评论</a></li>

                    <li><a id="TabLinks" href="">链接</a></li>
                    <li><a id="TabFavorites" href="">收藏</a></li>
                    <li><a id="TabGalleries" href="x">相册</a></li>
                    <li><a id="TabFiles" href="">文件</a></li>
                    <li><a id="TabConfigure" href="">设置</a></li>
                    <li><a id="TabPreferences" href="">选项</a></li>

                </ul>
                <div class="clear">
                </div>
            </div>
            <div id="content_area">
            {% csrf_token %}
                <div id="post_list">
                    <table cellpadding="0" cellspacing="0" border="0">
                        <tbody class="table-hover">
                        <tr>
                            <th class="post-title">标题</th>
                            <th class="publish-status">发布状态</th>
                            <th>评论数</th>
                            <th>阅读数</th>
                            <th>操作</th>
                            <th>操作</th>
                        </tr>
                        {% block table_tbody %}
                        {% for article in request.user.article_set.all %}
                           <tr>
                            <td class="post-tilte">
                                <a href="/blog/{{ request.user.username }}/p/{{ article.id }}/" class="post_title">{{ article.title }}</a>
                            </td>
                            <td>发布</td>
                           <td>{{ article.comment_count }}</td>
                           <td>{{ article.read_count }}</td>
                           <td ><a href="" class="delArticle" article_id="{{ article.id }}">删除</a></td>
                           <td><a href="/backManage/editArticle/?id={{ article.id }}">编辑</a></td>
                           </tr>
                        {% endfor %}
                         {% endblock table_tbody %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endblock %}
        </div>
    </div>
</div>
</body>

<script src="/static/jquery-3.2.1.min.js"></script>
<script>
    $(".delArticle").click(function () {
        if(window.confirm("你确认要删除吗?")){
        $.ajax({
            url:"/backManage/delArticle/",
            type:"POST",
            data:{
                article_id:$(this).attr("article_id"),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success:function (data) {
                if(data=="ok"){
                    $(this).parent().parent().remove()
                }
            }
        });
    }
    })
</script>
</html>

templates/updateSuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
ok
</body>
</html>